[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
auto_detect_solc = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@lido/=lib/lido/contracts/"
]

[fuzz]
runs = 2048

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
